openapi: 3.0.0
info:
  title: Pets API
  version: 1.0.0
  description: API documentation for Pets
paths:
  /api/pets:
    get:
      summary: Get all pets
      tags:
        - Pets
      responses:
        200:
          description: List of pets retrieved successfully

    post:
      summary: Create a new pet
      tags:
        - Pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Max
                specie:
                  type: string
                  example: Dog
                birthDate:
                  type: string
                  format: date
                  example: 2020-01-01
                adopted:
                  type: boolean
                  example: false
                owner:
                  type: string
                  example: 60d0fe4f5311236168a109ca
                image:
                  type: string
                  example: /images/max.png
      responses:
        201:
          description: Pet created successfully

  /api/pets/{pid}:
    get:
      summary: Get pet by ID
      tags:
        - Pets
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Pet retrieved successfully

    put:
      summary: Update a pet by ID
      tags:
        - Pets
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Max
      responses:
        200:
          description: Pet updated successfully

    delete:
      summary: Delete a pet by ID
      tags:
        - Pets
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Pet deleted successfully
